### ISSUE TITLE
Convert.seconds_to_timestring only converts to seconds

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#117]
`Convert.seconds_to_timestring` is a function used in few places: in the index, the recipe card (reccard), timeEntry, and a few export plugins.

Its use is to convert time, which is internally stored as ints representing seconds, to some nicer format such as `2 hours and 5 minutes`.

![screenshot of time rendered in seconds, instead of minutes](https://user-images.githubusercontent.com/2159577/85023996-c0abdc80-b175-11ea-861b-5f0b3c216547.png)

I'd say the priority is medium: it's not hard to fix, but the usability of the application is affected:

The current implementation could be fixed using something like this but internationalization might be tricky:

```python
from datetime import timedelta

def seconds_to_timestring(seconds: int, 
                          round_at: Optional[int] = None, 
                          fractions: Enum[TIME_FRACTIONS] = FRACTIONS_NORMAL):

    mins, secs = divmod(seconds, 60)
    hrs, mins = divmod(mins, 60)
    days, hrs = divmod(hrs, 24)

   time_string = ""
   if days:
      d = "days" if days > 1 else "day"
       time_string += f"{days} {d} "  # note the extra whitespace

  if hrs:
     h = "hours" if hrs > 1 else "hour"
     time_string += f"{hrs} {h} "  # note the extra whitespace

   ...
```

I don't think we care so much about period of times greater than a year. I also think that the fractions are not such a big deal (3/4 hour instead of 45 mins?).

**Comment by maweki** [comment]
Sorry, my bad. Just add `reverse=True` to the sorting. Apparently I mis-translated that.

```
    units.sort(key=lambda x: x[1]) #old cmp-func: lambda a,b: a[1]<b[1] and 1 or a[1]>b[1] and -1 or 0
```

**Comment by maweki** [comment]
Also replace `time_covered = time / int(divisor)` with `time_covered = time // int(divisor)`

**Comment by maweki** [comment]
That fixes it and keep all the old internationalization :)

```
>>> seconds_to_timestring(5000)
'1 hour, 23 minutes and 20 seconds'
```

**Comment by cydanil** [comment]
Thanks for your suggestions! I hadn't looked in depth at the code, and went a bit heavy-handed on my decision...

I can do a PR, if you like :)

**Comment by maweki** [comment]
Sure, go ahead.
