### ISSUE TITLE
Adding a new recipe doesn't work

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#12]
In the GUI, "Add a new recipe" action spawns a blank window.

**Comment by cydanil** [comment]
The reason for that blank Window are several, but one of them is that all the `ui/*ui` files were developed for GTK-2, whereas we're now using GTK-3 (or GTK-4?).

For instance, that window, `DescriptionEditorModule` refers to `ui/recCardDescriptionEditor.ui`, which itself references `GtkComboBoxEntry`.

I *think* `GtkComboBoxEntry` has been superseeded by `GtkComboBoxText`.

If no one is working on it, I'd like to convert that specific ui file to GTK3, and then document the migration process.

**Comment by kirienko** [comment]
I tried to fix that but got stuck at some point. Maybe I continue with that tomorrow. But feel free to fix that if you have courage ;-)

Or we can do PPP one day (I mean pair programming party)!

**Comment by cydanil** [comment]
PPP sounds pretty good actually: we're now changing a lot of stuff and stepping on one another's toes. @maweki, what do you think?

**Comment by maweki** [comment]
I don't think I will find the time for some dedicated programming. I just do it inbetween things. But feel free to do it. I'll mark my territory beforehand or will be fine with my toes being stepped on :)

I hope anyways that most fixes will be incremental and no more than a few lines of code each.

**Comment by cydanil** [comment]
Resolved!
