### ISSUE TITLE
syntax error in setup.py line 290?

### ISSUE THREAD

**Issue by OzarkShepherd** [kirienko/gourmet#142]
While building the flatpak, I got to the following error:

```
`Building module gourmet in /home/scott/Documents/flatpak/Gourmet2/.flatpak-builder/build/gourmet-1

Already on 'master'
Running: python setup.py install --prefix=/app
  File "setup.py", line 290
    print(line, end='')
                   ^
SyntaxError: invalid syntax
Error: module gourmet: Child process exited with code 1
`
```

**Comment by maweki** [comment]
What's `python` in your toolchain? It's supposed to be python3 and we're not sure exactly what we're targeting but something about 3.7 or 3.8.

Edit: Also the setup does probably not work anyway (see #107)

**Comment by OzarkShepherd** [comment]
I was using Python 2.7, based on the install.md and readme files.  I'll try python 3.7 then.

**Comment by maweki** [comment]
This fork here is the python3 port. But if you come across such stuff (as the readme), feel free to submit a PR with those changes. We haven't had a pass at the documentation yet.

**Comment by OzarkShepherd** [comment]
The flatpak I am working on can install this fork with python 3.7, but it gets cursor errors when trying to start.  That is possibly due to me not knowing the proper dependencies, do you know them offhand? 

Also elib.intl is written in python2, so it has to be left out of the flatpak or it won't compile.  However it gives errors when elib.intl is left out, but I don't think that is causing the following error

`Gdk-CRITICAL **: 11:34:13.313: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed`

**Comment by maweki** [comment]
The error you describe looks like there's no display availabe, I don't know.

About dependencies: I tried in #108 to run the setup with a container (but that was for building, so maybe not all but at least gtk3) and the following had to be installed manually:

* intltool
* file
* gtk3
* cairo-devel gcc python3-devel gobject-introspection-devel cairo-gobject-devel

And you also need to install the python packages in `requirements.txt`
