### ISSUE TITLE
requirements.txt out of date

### ISSUE THREAD

**Issue by dabrown645** [kirienko/gourmet#154]
Being new to the python 3  project I was working on installing the required software and based on information in the slack channel there are some packages missing from the requirements.txt file. There should also be a development.txt file to separate the packages needed for development from those for production.

**Comment by dabrown645** [comment]
After getting everything installed this is the dependency graph I came up with:

Development
===========
dogtail==0.9.10
flake8==3.8.3
  - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
  - pycodestyle [required: >=2.6.0a1,<2.7.0, installed: 2.6.0]
  - pyflakes [required: >=2.2.0,<2.3.0, installed: 2.2.0]
mypy==0.782
  - mypy-extensions [required: >=0.4.3,<0.5.0, installed: 0.4.3]
  - typed-ast [required: >=1.4.0,<1.5.0, installed: 1.4.1]
  - typing-extensions [required: >=3.7.4, installed: 3.7.4.2]
pytest==5.4.3
  - attrs [required: >=17.4.0, installed: 19.3.0]
  - more-itertools [required: >=4.0.0, installed: 8.4.0]
  - packaging [required: Any, installed: 20.4]
    - pyparsing [required: >=2.0.2, installed: 2.4.7]
    - six [required: Any, installed: 1.15.0]
  - pluggy [required: >=0.12,<1.0, installed: 0.13.1]
  - py [required: >=1.5.0, installed: 1.9.0]
  - wcwidth [required: Any, installed: 0.2.5]

Production
==========
EbookLib==0.17.1
  - lxml [required: Any, installed: 4.5.2]
  - six [required: Any, installed: 1.15.0]
giofile==0.2.0
  - pygobject [required: Any, installed: 3.36.1]
    - pycairo [required: >=1.11.1, installed: 1.19.1]
gobject==0.1.0
keyring==21.2.1
  - jeepney [required: >=0.4.2, installed: 0.4.3]
  - SecretStorage [required: >=3, installed: 3.1.2]
    - cryptography [required: Any, installed: 3.0]
      - cffi [required: >=1.8,!=1.11.3, installed: 1.14.0]
        - pycparser [required: Any, installed: 2.20]
      - six [required: >=1.4.1, installed: 1.15.0]
    - jeepney [required: >=0.4.2, installed: 0.4.3]
pgi==0.0.11.2
pyglet==1.5.7
pygtkspellcheck==4.0.5
  - pyenchant [required: Any, installed: 3.1.1]
reportlab==3.5.46
  - pillow [required: >=4.0.0, installed: 7.2.0]
scrape-schema-recipe==0.1.1
  - extruct [required: Any, installed: 0.9.0]
    - html-text [required: >=0.5.1, installed: 0.5.2]
      - lxml [required: Any, installed: 4.5.2]
    - lxml [required: Any, installed: 4.5.2]
    - mf2py [required: Any, installed: 1.1.2]
      - BeautifulSoup4 [required: >=4.6.0, installed: 4.9.1]
        - soupsieve [required: >1.2, installed: 2.0.1]
      - html5lib [required: >=1.0.1, installed: 1.1]
        - six [required: >=1.9, installed: 1.15.0]
        - webencodings [required: Any, installed: 0.5.1]
      - requests [required: >=2.18.4, installed: 2.24.0]
        - certifi [required: >=2017.4.17, installed: 2020.6.20]
        - chardet [required: >=3.0.2,<4, installed: 3.0.4]
        - idna [required: >=2.5,<3, installed: 2.10]
        - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
    - rdflib [required: <5.0.0, installed: 4.2.2]
      - isodate [required: Any, installed: 0.6.0]
        - six [required: Any, installed: 1.15.0]
      - pyparsing [required: Any, installed: 2.4.7]
    - rdflib-jsonld [required: Any, installed: 0.5.0]
      - rdflib [required: >=4.2.2, installed: 4.2.2]
        - isodate [required: Any, installed: 0.6.0]
          - six [required: Any, installed: 1.15.0]
        - pyparsing [required: Any, installed: 2.4.7]
    - six [required: Any, installed: 1.15.0]
    - w3lib [required: Any, installed: 1.22.0]
      - six [required: >=1.4.1, installed: 1.15.0]
  - isodate [required: >=0.5.1, installed: 0.6.0]
    - six [required: Any, installed: 1.15.0]
  - requests [required: Any, installed: 2.24.0]
    - certifi [required: >=2017.4.17, installed: 2020.6.20]
    - chardet [required: >=3.0.2,<4, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
  - setuptools [required: >=30.3.0, installed: 47.1.1]
  - validators [required: >=0.12.4, installed: 0.16.0]
    - decorator [required: >=3.4.0, installed: 4.4.2]
    - six [required: >=1.4.0, installed: 1.15.0]
selenium==3.141.0
  - urllib3 [required: Any, installed: 1.25.10]
Sphinx==3.1.2
  - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
  - babel [required: >=1.3, installed: 2.8.0]
    - pytz [required: >=2015.7, installed: 2020.1]
  - docutils [required: >=0.12, installed: 0.16]
  - imagesize [required: Any, installed: 1.2.0]
  - Jinja2 [required: >=2.3, installed: 2.11.2]
    - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - packaging [required: Any, installed: 20.4]
    - pyparsing [required: >=2.0.2, installed: 2.4.7]
    - six [required: Any, installed: 1.15.0]
  - Pygments [required: >=2.0, installed: 2.6.1]
  - requests [required: >=2.5.0, installed: 2.24.0]
    - certifi [required: >=2017.4.17, installed: 2020.6.20]
    - chardet [required: >=3.0.2,<4, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
  - setuptools [required: Any, installed: 47.1.1]
  - snowballstemmer [required: >=1.1, installed: 2.0.0]
  - sphinxcontrib-applehelp [required: Any, installed: 1.0.2]
  - sphinxcontrib-devhelp [required: Any, installed: 1.0.2]
  - sphinxcontrib-htmlhelp [required: Any, installed: 1.0.3]
  - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
  - sphinxcontrib-qthelp [required: Any, installed: 1.0.3]
  - sphinxcontrib-serializinghtml [required: Any, installed: 1.1.4]
SQLAlchemy==1.3.18

**Comment by cydanil** [comment]
Addressed in #155
