### ISSUE TITLE
Loading images from database should be done in memory

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#159]
Recipes may have images attached to them.
These are shown in the main window, but also within the Recipe Card.

When loading the images for the recipe card (`reccard`), the conversion from image data bytes to `Gtk.Image`, done in [`get_pixbuf_from_jpg`](https://github.com/kirienko/gourmet/blob/73080d10e1df84c5101e4e172d5f266243614aae/gourmet/ImageExtras.py#L60), makes a temporary file, when it could be done in memory, as the file is not deleted until reboot (the span of weeks in my case). 

Then `write_image_tempfile` can be removed altogether.
`get_string_from_pixbuf` should also be updated.

**Comment by cydanil** [comment]
`get_pixbuf_from_jpg` can be updated so:

```python
def get_pixbuf_from_jpg(raw: bytes) -> GdkPixbuf.Pixbuf:
    """Create a GdkPixbuf.Pixbuf from bytes"""
    glib_bytes = GLib.Bytes.new(raw)
    stream = Gio.MemoryInputStream.new_from_bytes(glib_bytes)
    pixbuf = GdkPixbuf.Pixbuf.new_from_stream(stream)
    return pixbuf
```
`get_pixbuf_from_jpg` could be renamed `pixbuf_from_bytes` or `bytes_to_pixbuf`.

`get_string_from_pixbuf` can be updated so:
```python
def get_string_from_pixbuf(pb: GdkPixbuf.Pixbuf) -> bytes:
    return pb.save_to_bufferv('jpeg', [], [])
```

`get_string_from_pixbuf` can simply be removed and all calls to it be replaced by `pb.save_to_bufferv('jpeg', [], [])`.

**Comment by avats-dev** [comment]
Hey @cydanil , I can work on this issue and would like to. 
</br>
So, `get_pixbuf_from_jpg` need to be updated [here](https://github.com/kirienko/gourmet/blob/73080d10e1df84c5101e4e172d5f266243614aae/gourmet/ImageExtras.py) as you mentioned above and `write_image_tempfile` needs to be removed. 
> **Well, I couldn't get what needs to be done with `get_string_from_pixbuf`.**

**Comment by cydanil** [comment]
Hi Aditya! 
Thanks, go ahead :)

`get_string_from_pixbuf` can be removed, and all places calling it should directly call `pixbuf.save_to_bufferv`.

**Comment by avats-dev** [comment]
Ok @cydanil , I will do this and update soon.

**Comment by avats-dev** [comment]
Hey @cydanil , there is a problem in removing `write_image_tempfile` as it is used [here](https://github.com/kirienko/gourmet/blob/73080d10e1df84c5101e4e172d5f266243614aae/gourmet/ImageExtras.py#L32), so what should I do?

> Btw, I've updated the other functions and updating other files wherever those were imported and called.

**Comment by cydanil** [comment]
`get_image_from_string`, which by the way could be renamed to something like `get_image_from_bytes`, make use of `io.BytesIO`, which used to not work on Windows a while back, hence the reading from file.
Now it's fine, the whole thing could be refactored as follows:

```python
def get_image_from_bytes(raw: bytes) -> Image.Image:
     sfi = io.BytesIO(raw)
     sfi.seek(0)
     return Image.open(sfi)
 ```

**Comment by avats-dev** [comment]
@cydanil thanks for the help, I will update soon with the PR.🖖
