### ISSUE TITLE
Base Directory settings different for windows and linux (settings.py)

### ISSUE THREAD

**Issue by dabrown645** [kirienko/gourmet#161]
I am looking at gglobals and how it impacts the tests and I noticed that the libaries in settings.py are different for windows and linux. is there a reason? Shouldn't the only thing that is different is how to establish the base_dir?

Linux:
  base_dir = os.path.join(os.path.dirname(__file__), '..')
  data_dir = os.path.join(base_dir, 'data')
  ui_base = os.path.join(base_dir, 'ui')
  doc_base = os.path.join(base_dir) **vs base_dir/doc**
  locale_base = os.path.join(base_dir, 'build', 'mo')
  plugin_base = os.path.join(base_dir, 'build', 'share', 'gourmet')
  lib_dir = os.path.join(base_dir, 'gourmet')
Windows:
  base_dir = os.path.dirname(sys.executable);
  data_dir = base_dir; vs base_dir/data
  ui_base = os.path.join(base_dir, 'ui');
  doc_base = os.path.join(base_dir, 'doc');
  locale_base = os.path.join(base_dir, 'locale'); **vs base_dir/build/mo**
  plugin_base = os.path.join(base_dir) **vs base_dir/build/share/gourmet**
  **lib_dir missing**
**icon_base = os.path.join(data_dir, 'icons') This seems to be common**

**Comment by cydanil** [comment]
Gourmet was launched through MSYS2, as [described here](https://github.com/kirienko/gourmet/blob/master/INSTALL.md#windows-10), and these issues are now gone :)
