### ISSUE TITLE
Import File routines not working

### ISSUE THREAD

**Issue by Oldbwl** [kirienko/gourmet#192]
**Actions Taken**
1. Run Gourmet
2. Select File/Import File
3. Navigate to Folder containing .mmf/.xml/.mcb file

**Expected results**
1. File selector should show importable files and allow the list to be filtered
2. Importable files should be imported and appear in Main screen

**Actual Results**
1. No files shown
2. Not possible to filter for file types
3. Not possible to import Files.
4. Closing File selector should return to Main screen, actual result is a new Main screen is spwned. Closing new screen closes application completely

**Comment by Oldbwl** [comment]
Running Gourmet from the terminal I can see that the import plugins are not yet avail. I do not know if Item 4. of actual results is a consequence of the absence of the import plugins

**Comment by cydanil** [comment]
To test once #193 is resolved. Thanks!

**Comment by cydanil** [comment]
This has to do with internationalization: 
The templates for plugins exist, however they are not processed during the creation of the flatpak.
As such, the files `*.gourmet-plugin` do not exist, hence the `Plugin [...] not found` message.

`python setup.py build_i18n` has to be ran first.

**Comment by cydanil** [comment]
Could you tell me what would be two good importers and two exporters that would be nice to have working first?

**Comment by cydanil** [comment]
Files export seem to work as they used to! (PDF are a different story, alas).
On imports, there are some GUI bugs, although recipes are imported fine from MealMaster files:
- A new main window is drawn;
- Import progress bar and actions are not cleaned when an import is cancelled.

**Comment by cydanil** [comment]
The import from files works again, test with MealMaster files from [http://www.ffts.com/recipes](http://www.ffts.com/recipes/apetizer.zip).  

I will release an alpha 2 version, and I'll get back to you to test imports again.

Thanks!
Cyril
