### ISSUE TITLE
New Recipe Card - Drop Down lists cannot be amended

### ISSUE THREAD

**Issue by Oldbwl** [kirienko/gourmet#194]
**Actions**
1. Run Gourmet
2. Click "New Recipe" from Recipe Index Screen
3. Select and Drop down list item on Card

**Results**
1. All drop down lists are either blank or precompleted and cannot be altered

**Expected Results**
1. Drop downs should accept input to update list

**Comment by Oldbwl** [comment]
I expect the Devs have released this version with limited functionality and the lists are either absent and or fixed

**Comment by cydanil** [comment]
Thanks! It's now resolved. A few more issues need addressing, and we'll make another alpha release following that.
