### ISSUE TITLE
New Recipe - Ingredients - Ctrl+C paste does not work

### ISSUE THREAD

**Issue by Oldbwl** [kirienko/gourmet#195]
**Actions**
1. Open Gourmet
2. Select New Recipe
3. Select Ingredients
4. Insert Cursor in text input box
5. Press Ctrl+C to paste in a Single Ingredient from another documet

**Results**
No Action + Ctrl+C ignored

**Expected Results**
1. Text in plain form should be pasted in to Input box (noted that right clicking on box does allow Paste to be selected and does work.

**Comment by cydanil** [comment]
The creation of `Gtk.Clipboard` is incorrect.  

It should now be, in `reccard.py`:
```python
self.cb = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
```

However, `reccard.TextEditor.do_paste` is also incorrect: the logic to find the widget where to paste, the `hasattr(parent, 'focus_widget')` does not work as intended. I believe it's meant to be:

```python
 def do_paste(self, action: Gtk.Action):
        if self.edit_widgets:
            widget = self.edit_widgets[0]
        else:
            widget = self.edit_textviews[0]

        while True:
            parent = widget.get_parent()
            if widget.has_focus() or parent is None:
                break
            widget = parent

        if isinstance(widget, Gtk.TextView):
            buf = widget.get_buffer()
            buf.paste_clipboard(self.cb, None, widget.get_editable())
        if isinstance(widget, Gtk.Editable):
            widget.paste_clipboard()
```

**Comment by cydanil** [comment]
Furthermore, `IngredientEditorModule.paste_ingredients_cb` should be modified so:

```python
    def paste_ingredients_cb(self, action: Gtk.Action):
        self.cb = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
        def add_ings_from_clippy(cb, text):
                def do_add():
                    for l in text.split('\n'):
                        if l.strip():
                            self.add_ingredient_from_line(l)
                add_with_undo(self, lambda *args: do_add())
        self.cb.request_text(add_ings_from_clippy)
```

Although this method could be further refactored
