### ISSUE TITLE
Drag and Drop of Ingredients (and groups) Fails

### ISSUE THREAD

**Issue by Oldbwl** [kirienko/gourmet#197]
**Actions**
1. Open Gourmet
2. Select any existing recipe or create New
3. Edit Recipe Ingredients
4. Populate Ingredients list
5. Left Click and Hold single ingredient, attempt move to new position or place over a Group Heading
6. Let go mouse button to complete ingredient move

**Result**
1. Ingredient moves with mouse drag, insertion line appears (or box in cases of Group Headings)
2. Ingredient does not move to new position
3. Closing screen elicits prompt to save changes (the changes do not save upon click of button)

**Expect Results**
1. The Ingredient should be move to the new position

**Comment by cydanil** [comment]
Thanks for reporting this issue, it's now fixed!
