### ISSUE TITLE
Add New Recipe Description Input Problems

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#226]
Dropdowns for yield, category, cuisine, and source do not allow adding to the list.

Unable to enter any text into the displayed box. Dropdown appears and one must choose from the supplied list. If a new entry is needed, for the relevant list, it cannot be entered.

Expected behavior is that dropdown choices change, showing typed text for new entry (or until nothing matches) or user can choose from full list if nothing is entered.

**Comment by cydanil** [comment]
Thanks! This was also reported in #194 and #90 as well. There has been an API change in Gtk3 that needs addressing. It's on the list for the next alpha release.
