### ISSUE TITLE
Unable to View New Recipe After Saving

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#227]
Save appears to add new recipe to index, but unable to view new recipe.

Populate recipe inputs and click save. New recipe appears in the index, but double-clicking it only displays the edit window.

### Environment
gourmet-5ad618be
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by cydanil** [comment]
It seems that upon closing the recipe editor window, `RecGui.rc` is not cleared properly.

**Comment by cydanil** [comment]
[`The hide method`](https://github.com/kirienko/gourmet/pull/132/files#diff-f8ba652dac21fa98c3f63d5592c79174R134-R140) in PR #132 brought in this issue.
