### ISSUE TITLE
Fix test_foodnetwork_plugin.py

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#24]
1 failed, 1 passed, 10 warnings

The failure is related to the `BeautifulSoup4` changes:
```
AttributeError: type object 'BeautifulSoup' has no attribute 'BeautifulSoup'
```
Priority: low

**Comment by FriedrichFroebel** [comment]
I think this issue can be closed, as the test itself works for now (even if only for the old saved page version).
