### ISSUE TITLE
RecEditor: "<Control>v" always pastes to the ingredient tab after it receives the focus

### ISSUE THREAD

**Issue by gnarlyquack** [kirienko/gourmet#244]
### Steps to Reproduce

1. Select "new" from the toolbar to start entering a new recipe.
2. Switch to the "Instructions" tab and paste into the text edit widget using `<Control>v`. Text is successfully pasted.
3. Switch to the "Ingredients" tab.
4. Switch back to the "Instructions" tab and try to paste into the text edit widget again using `<Control>v`. Nothing happens.
5. Return to the "Ingredients" tab. Text has been pasted as ingredients.

### Expected Behavior

Text should paste to the correct notebook tab.

### Current Behavior

Text pastes to the ingredient tab.

### Possible Solution
`IngredientEditorModule` registers an action that explicitly maps the `<Control>v` accelerator to the "PasteIngredient" action. When switching to the "Ingredients" tab, this action is then added to the `UIManager` (it should be noted, GTK has deprecated this component). This seems to permanently map the `<Control>v` accelerator to the "PasteIngredient" action even if the action is removed from the `UIManager` when switching away from the tab. Eliminating the explicit accelerator for "PasteIngredient" might fix this? However, given the deprecation of `UIManager`, its use should be eliminated altogether.

### Environment

* Operating System: Arch Linux
* Version or commit id: commit af71e6cf7881511e6011c01fa1ad9159340555be
* Installed as Flatpak or Python package?: Installed as a Python package (in a virtual environment) from source.

**Comment by gnarlyquack** [comment]
Upon further testing, it looks this is just an issue when pasting with the accelerator key (Ctrl-V). Pasting with the toolbar button appears to work fine.

**Comment by cydanil** [comment]
This issue is due to API changes (+ our code) between Gtk2 and 3.  

In the Clipboard callback, `TextEditor.do_paste` , the code takes the first widget available in the window, and recurses up to find the widget with focus.
`self.edit_textviews[0]` refers to the Ingredients TextView.
However, it should first get a handle on the window, and get its focused widget:

```python
def do_paste(self, action: Gtk.Action): 
       window = self.get_window()  # Something like that
       widget = window.get_focus()
       [...]
```

**Comment by gnarlyquack** [comment]
After more research, I've updated my initial description. The problem doesn't seem to be in `TextEditor.do_paste`, as that function is never called when pasting with `<Control>v` after the "PasteIngredient" action is added to the `UIManager` for `RecEditor`.
