### ISSUE TITLE
Removing picture from recipe does not work

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#256]
Referencing an old issue from upstream:
https://github.com/thinkle/gourmet/issues/255

**Comment by zombiewoof** [comment]
Not only does removing not work, one cannot change the image either.

Attempted to change the image for a recipe and save button never greyed out. Closing edit window warned of unsaved data - chose save. Image did not change in index or recipe card window. Closed recipe card and re-opened, no change (as I expected).
