### ISSUE TITLE
Printing Not Working

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#257]
Print is greyed out in File menu. In recipe card, Recipe menu, printing is not greyed out, but clicking results in error:

![Gourmet Print Error 2020-10-15 09-36-35](https://user-images.githubusercontent.com/4460090/96137046-257c0700-0eca-11eb-89f1-49761bb074ff.png)

Clicking OK results in:

![Gourmet Print Error 2 2020-10-15 09-39-52](https://user-images.githubusercontent.com/4460090/96137325-87d50780-0eca-11eb-9253-9a35c3f3ce52.png)

Attempted to activate a print plugin to find that "Printing & PDF Export" is already activated, clicked to deactivate. Got an error stating that there was a problem deactivating. Closing and re-opening Gourmet shows plugin deactivated, but clicking, to activate, results in error stating that there was a problem activating. Closing and re-opening Gourmet shows plugin still deactivated.

Do not see any other plugin that indicates that it is associated with printing. Maybe something was missed in the install pack?

Install followed instructions on installation instruction page, for flatpak (since flatpak already installed, did not reinstall), but executed both command lines below that, after downloading the Gourmet flatpak file. Choosing "y" for install of io.github.thinkle.Gourmet/x86_64/master resulted in no bytes downloaded but successful install indicated.

![Gourmet Update 2020-10-15 10-15-25](https://user-images.githubusercontent.com/4460090/96144671-6aa43700-0ed2-11eb-8870-96cf517aefb2.png)

### Expected Behavior
Open print dialog for printing after allowing activation of a print plugin.

### Environment
gourmet-2db9db8f.flatpak Help->About shows version 0.17.5 (installed over gourmet-5ad618be.flatpak as if an upgrade) 
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by zombiewoof** [comment]
I suspect that the inability to print is related to no plugins. I have commented under #264 regarding how to get plugins installed.

This issue will likely need to be closed, once instructions on how to get plugins installed is provided as requested in issue #264.

**Comment by cydanil** [comment]
Printing from the flatpak installation is a work in progress: there is some dependent software that needs to be installed alongside.

It proved to be difficult, but is on the roadmap, see #222 .

**Comment by zombiewoof** [comment]
I see. Thanks for the information. I thought that maybe I'd not done the installation correctly.

Printing is not such a big deal, for me. I do print a recipe from time to time, but export to PDF is more important, as far as I'm concerned, as I more often share recipes by email with a PDF attachment.

**Comment by cydanil** [comment]
This is now resolved, I'll make a Flatpak available in the coming days :)
