### ISSUE TITLE
Rating Stars Color Suggestion

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#258]
With some themes (white background) the stars, in particular half-stars, do not show up well. Is it possible to check light/dark theme and use the current yellow color for dark themes and maybe blue for light themes? If checking theme isn't easily handled, maybe offer a setting for choosing one color or the other?

**Comment by cydanil** [comment]
Yes, this is also true of links, as mentioned in #139 (the solution proposed there is incorrect.)  
This is more difficult than one would think: there are no standards across desktop environments to get the theme brightness.
It's easy to know what are the colours of the current theme, but hard to figure out if it's a bright or dark theme.  

For instance, it's possible to get the theme name:
```python
from gi.repository import Gtk
settings = Gtk.Settings.get_default()

settings.get_property('gtk-theme-name')
'Mint-Y'  # or 'Mint-Y-Dark'
```
But it's not guaranteed that the theme name contains the `Dark` keyword.

For the links, I was considering using a colour that renders nicely in both darks and light.

**Comment by zombiewoof** [comment]
Looks like it's not worth the coding to get the theme name on the off chance that it might contain text that would indicate light or dark theme.

That leaves 2 options, I think.

1) Choose a color that renders nicely in dark and light themes, as you suggest. What do you think about  #74b7df ? Should be light enough to show up in a dark theme and is dark enough for light themes - at least for stars, might be OK for links too.

2) Provide 2 color options, one light the other dark, and let the user choose which to use, saving the choice as a setting. If the option is left up to the user, that same color could be used for links, maybe?

I think that either solution is good - some might prefer one or the other. Obviously coding would be simpler for the single color - set to a variable in the beginning and plop the variable in wherever needed.

**Comment by cydanil** [comment]
I've made stars of the colour you suggested, it looks like this:

![image](https://user-images.githubusercontent.com/2159577/97059498-dbadb380-1590-11eb-950d-2aa351571a52.png)


![image](https://user-images.githubusercontent.com/2159577/97059526-eec08380-1590-11eb-9ce0-bf934387a35c.png)


Is that what you'd expect? :)

**Comment by zombiewoof** [comment]
Exactly what I was referring to - great work!

I take it that you figured out a way to tell if the background was dark or light to set the star color.

**Comment by cydanil** [comment]
Sweet, thanks for your feedback!
