### ISSUE TITLE
Browse Recipes View

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#259]
Extremely happy to see this show up in the new alpha. Just making note of some things that are probably already in the works for this section.

Browse recipes displays in 2 columns instead of based on width of window. Icons do not display an image from their group. Although items in each group are alphabetized, recipes are not.

### Steps to Reproduce
Open Browse Recipes view tab.
Display is in 2 columns no matter how wide you make the window.
Same for any group chosen (level 2 of display)
Same for recipes display (level 3)

### Expected Behavior
Display should create more columns as window is made wider.
In level 2 of display, Python 2 version picked up a recipe icon image, from each group, to display.
In level 3 of display, it would be nice to have recipes in alphabetical order (IIRC, I got a very simple patch for the Python 2 version from one of the Python 2 developers that did this).
### Environment
gourmet-2db9db8f.flatpak Help->About shows version 0.17.5 (installed over gourmet-5ad618be.flatpak as if an upgrade)
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by gnarlyquack** [comment]
Actually, it does expand to more than 2 columns, you just need to get the window wide enough. That said, the spacing between the icons can probably be significantly reduced, as can perhaps the size of the icons as well.
![recipe-browser](https://user-images.githubusercontent.com/412354/96403950-3dd87400-119f-11eb-88fd-f2150bb6428d.jpg)

**Comment by zombiewoof** [comment]
I stand corrected - I did manage to get 3 columns as your screenshot shows, in a test this morning.

It is the horizontal spacing that should be significantly reduced - vertical spacing is OK.

The size of the icons appears to be the same as the python2 version, at least on my screen, so I don't see a need to reduce their size.

**Comment by gnarlyquack** [comment]
There's nothing with the icons per se, but something about them seems off stylistically to me, although that's probably mostly a matter of one's personal preference. :-)

**Comment by zombiewoof** [comment]
I agree that they are a bit large, but my personal preference isn't particularly relevant here. I'm commenting based on the assumption that the python3 version will be an updated version of the old one - but I don't have any problem with tweaks to make things look/work better... :-)

Side by side comparison (I have both python2 and python 3 versions on this box) shows them to be the same image and size in both versions. The exception being on the second screen, where groups are shown with generic icons. The python2 version picks an image from each group for these.

Maybe different icons could be chosen for the first screen - actual photo type images to be more in line with the images that show up for the recipes? I kinda like the second screen with images picked from each group.

My concern about reducing the size is that the reduction would also likely take place on the icon images that show up for the recipes. That could make some images become too small to be meaningful. They are already covered by prep time, cook time and stars images if those are defined for the recipe. Space for those images would be reduced, as well.

The above concern stems from how I'd handle those screens. I'd define the icons, for each screen as needed, put them in an array (or some similar setup) and pass that to a subroutine/method/function (your pick of terminology) to create the actual display. To keep column setup simple, the icons would need to be the same size for all screens, which could be set when the display is created or when they are defined. My coding experience is limited to BASIC and PHP, but I assume python logic setup would be similar.

**Comment by cydanil** [comment]
Would you expect something like the views below?

![browser](https://user-images.githubusercontent.com/2159577/97116409-2d734c80-16fd-11eb-9078-967b8914e39a.gif)

**Comment by zombiewoof** [comment]
Yes - assuming that the number of columns changes with window width, on all screens.

Display of Cook Time, Prep Time and Rating are exactly what I would expect. It appears that these screens have the items sorted by number (4.5 stars before 5 stars and less time before more time). Excellent work!

The Category, Cuisine and Source should pick up an icon image from a recipe within that group to match python2 version behavior. I don't know how that is currently done, maybe random choice or lowest record number found in the DB that has an image. Since the posted video doesn't show these groups, I cannot tell if they are sorted, or not, but if the same code is used as for the other groups, they should be.

The screen displaying recipe icons is not sorted. This was not something originally in the python2 version, but I got a patch to sort it from one of the developers (just a few lines as I recall) and I think it may have been added in a later version. Sorting makes finding a recipe easier when you have many recipes on the browse screen.

Here are screenshots from my python2 version, with the window width that I normally use, for illustration for the other groups and icon display on the main Browse Tab screen.

Browse Tab:
![Gourmet 2020-09-13 12-38-19](https://user-images.githubusercontent.com/4460090/97120063-e2e8d480-16ea-11eb-8c3d-b58df2c46836.png)

With Category Group Chosen (Note these are sorted):
![Gourmet 2020-09-13 12-38-43](https://user-images.githubusercontent.com/4460090/97120085-1297dc80-16eb-11eb-85aa-06e98ac50961.png)

With Beef Recipes Chosen (Sorted, but may be from patch, see above):
![gourmet 2020-09-13 12-39-14](https://user-images.githubusercontent.com/4460090/97120097-38bd7c80-16eb-11eb-95e3-3b55239d4455.png)

When adding bells and whistles, it might be an idea to add images for sources - like a photo of the book the recipe came from, maybe be able to add a little bio for individuals. This is NOT something that is really needed, just an idea for an extra, when the rest of the application is out of beta.

**Comment by cydanil** [comment]
Thanks for the screenshots, I was able to fix the images being displayed as icons!

![image](https://user-images.githubusercontent.com/2159577/97181132-3ca8d780-179b-11eb-8202-3a7f041ec587.png)

The number of columns is indeed adjusted when the window is resized :)

**Comment by zombiewoof** [comment]
Fantastic!

I think that the icon order, on the home screen, is logical, with prep and cook times together, as per the screen video that you posted.

If icons are sorted within groups (category, cuisine, etc) and recipes, I believe you are done here. :)

**Comment by cydanil** [comment]
Thanks for your help :)
