### ISSUE TITLE
Consider vendoring pygtkspellcheck

### ISSUE THREAD

**Issue by gnarlyquack** [kirienko/gourmet#278]
Because pygtkspellcheck imports itself in its `setup.py`, attempting to install the package using `pip` fails if its dependencies (enchant, gobject) aren't already installed. Although I [opened an issue](https://github.com/koehlma/pygtkspellcheck/issues/36) some time ago, per the [author's comment](https://github.com/koehlma/pygtkspellcheck/issues/37#issuecomment-319223690), it appears he may not be maintaining it anymore.

Alternatively, this could be dropped as a dependency if there's no desire to maintain the spellcheck plugin.

**Comment by cydanil** [comment]
I see. It's also true of some other package (I can't remember which exactly from the top of my head).  
We should perhaps consider having a `pyproject.toml`?

**Comment by gnarlyquack** [comment]
We may want to add a `pyproject.toml` regardless (for ensuring `setuptools` and `wheel` are installed, etc), but I don't know that I like the idea of using it to pre-install packages for dependencies with broken installations. Vendoring it and/or submitting a patch seem cleaner to me, although the latter option assumes the maintainer is in a position to apply it and issue a new release. Vendoring it probably wouldn't require a patch (at least, not for this) since we would no longer be explicitly installing it.

**Comment by cydanil** [comment]
I think we should go for the `pyproject.toml`: I find that Gourmet, as a project, does not have the resources to support and maintain `pygtkspellcheck` or other external projects.  
For the time being, there's already too much crummy code within the project.  

I'm leaving the issue open as a reminder to work on `pyproject.toml`.

**Comment by gnarlyquack** [comment]
The point of vendoring it is that it would be a local copy of the code that lives in our own source tree. This would not mean maintaining it for other projects. It's GPL 3, so the licensing permits this.

**Comment by cydanil** [comment]
I understand. I meant that we risk missing out on future updates, and I believe changes that we would make ought to go upstream, even though the project looks abandoned (or perhaps it's mature enough to not require constant updates).

Yes, it's problematic during development, but I would expect packagers to take care of dealing with dependencies for us when distributing the application.

**Comment by gnarlyquack** [comment]
Well, I'm not saying it's an ideal solution, and it can always be re-evaluated if things change. Perhaps somebody can make a PR and see if it gets merged and uploaded to PYPI.

We can also accommodate downstream packagers with something like:
```python
try:
    import gtkspellcheck
except ImportError:
   from gourmet.vendor import gtkspellcheck
```
It might also be that case that including required packages in `project.toml` might be interpreted by packagers as being Build-Depends, which they're really not. So it's not necessarily a clear-cut win IMO.

**Comment by gnarlyquack** [comment]
I've [opened a PR](https://github.com/koehlma/pygtkspellcheck/pull/41) that should resolve the issue. Fingers crossed we can get a release...

**Comment by koehlma** [comment]
I just merged your PR and published a new release with the fix to PyPi.

**Comment by cydanil** [comment]
That's fantastic! Thanks for the prompt reaction :)

**Comment by gnarlyquack** [comment]
I've confirmed that installation works smoothly now. Thanks so much!
