### ISSUE TITLE
Consider using Opus for sound file formats

### ISSUE THREAD

**Issue by gnarlyquack** [kirienko/gourmet#284]
GStreamer requires codec plugins to actually play any sound, and [several varieties of plugin bundles](https://gstreamer.freedesktop.org/documentation/additional/splitup.html) are provided based on a combination of code quality and licensing restrictions. Pretty much the only audio codecs in the [base set](https://gstreamer.freedesktop.org/data/doc/gstreamer/stable/gst-plugins-base-plugins/html/) are Opus and the older Vorbis (wav and mp3 appear to be in the [good set](https://gstreamer.freedesktop.org/data/doc/gstreamer/stable/gst-plugins-good-plugins/html/)). I think we should target the base set to minimize dependencies, and using the newer Opus format seems like a logical choice. As an added benefit, converting the files away from wav will reduce their size quite considerably.

**Comment by cydanil** [comment]
This makes sense, I agree
