### ISSUE TITLE
Fix test_interactive_imported

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#30]
The test looks relatively simple, but again there is an import-related problem somewhere.

```
TypeError: catching classes that do not inherit from BaseException is not allowed
```

Priority: medium

**Comment by nsirletti** [comment]
Is the issue still active ?

I can't seem to find a mention of this test in the CI build.

When I run it locally (`Ubuntu 19.10`  `Python 3.7.5`  `nose 1.3.7`) I have an import problem with the `poppler` binding package which seems not to be included in ubuntu repos under this name any longer, but once I solve it using `popplerqt5` instead the test passes without ever raising a `TypeError`, or any exception for the matter.

**Comment by kirienko** [comment]
The particular `TypeError` is now fixed I suppose, but that one only masked the actual problems, which are still there. I'll try to update the issue tomorrow.
