### ISSUE TITLE
Browse Ratings Descriptions Bug

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#306]
Rating descriptions show both decimal number and fraction.

Open RC 1. Choose Browse. Choose Rating. Rating descriptions show decimal number for all ratings. This value carries over to the button displayed with recipes on next screen.

### Expected Behavior
Whole number rating should show integer. Rating with half star should show integer and '1/2'.

### Current Behavior
Whole number rating displays decimal place (4.0 for example) and half star rating shows decimal number (3.5 for example) along with the expected '1/2'.

### Environment
gourmet-c3ece056
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by zombiewoof** [comment]
Great. Would it be too much trouble to remove the zero in front of '1/2' for a half star? Not a big deal, just looks better.

**Comment by cydanil** [comment]
Yes! It's done so:

![image](https://user-images.githubusercontent.com/2159577/98718017-23ed1400-238e-11eb-924a-66a5299768a5.png)

**Comment by zombiewoof** [comment]
The above screenshot looks great for the ratings shown. My earlier comment referred to 1/2 star as opposed to a whole number and 1/2, as in 3 1/2. To me, '1/2' looks better than '0 1/2' that showed in an earlier screenshot.
