### ISSUE TITLE
Add Recipe When not on Last Index Screen Creates 2 New Recipes

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#315]
Saving a new recipe when on an index screen, other than the last, creates 2 new recipes. One contains part of the input information, the other is empty. After this test failed, I did not perform another test while on the last index page.

The python2 version has some issues with saving recipes when not on the last index page, but not so severe. Usually, only the image and name is not saved, no duplicated 'New Recipe'.

### Steps to Reproduce
Choose new recipe in RC1, while not on last index screen. Input a recipe and save. Move to last index screen to find 2 recipes named New Recipe.

### Expected Behavior
Recipe should be saved with name and data that was input.

### Current Behavior
Save results in 2 recipes added to end of last index screen. The first new recipe is blank and the second only shows part of the data that was input.

NOTE: In this test I DID NOT attempt to add an image, but all other inputs were used (all others on description, ingredients, instructions and notes).

In the screenshot, the 2 recipes are the last entries on the index page. The recipe card on the left results from double-clicking the first 'New Recipe' and the recipe card on the right results from double-clicking the second.

![Screenshot from 2020-11-11 15-37-36](https://user-images.githubusercontent.com/4460090/98862349-c1028800-2434-11eb-998d-e93f1f8cd9fa.png)

### Environment
gourmet-c3ece056
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by cydanil** [comment]
Thanks!  
I'm able to reproduce the problem.

I think the problems comes from [an index error here](https://github.com/kirienko/gourmet/blob/ed1013b1f28bbc755a33fb31eab4b5a63f9e5c95/src/gourmet/plugins/key_editor/recipeEditorPlugin.py#L261).

**Comment by cydanil** [comment]
The `KeyEditor` plugin has numerous errors. Disabling the plugin makes the problem go away.  

I'll fix this plugin, and I think we'll be able to make a new release.
