### ISSUE TITLE
Fix test_reccard.py

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#32]
The error message is the same as in #22:
```
AttributeError: module 'gourmet.gglobals' has no attribute 'dbargs'
```
But the problem might be completely different.
That's also an old and complicated test.

Priority: high

**Comment by cydanil** [comment]
I'll take it

**Comment by cydanil** [comment]
I don't have the rights to update the project, though

**Comment by maweki** [comment]
> I don't have the rights to update the project, though

You can create a PR from your own fork, or what do you mean?

**Comment by cydanil** [comment]
I meant marking [the issue card](https://github.com/kirienko/gourmet/projects/1#card-37383258) as in progress.

**Comment by maweki** [comment]
> I meant marking [the issue card](https://github.com/kirienko/gourmet/projects/1#card-37383258) as in progress.

Oh, yeah, sorry. I did it now, but for permissions we need @kirienko .

**Comment by cydanil** [comment]
no worries, thanks :)
