### ISSUE TITLE
Plugins not recognized after installation from source on Linux with setup.py

### ISSUE THREAD

**Issue by vollkorn1982** [kirienko/gourmet#323]
When installing the current master with setup.py, the plugins are not recognized. The files seem to be at the right place, but they are not selectable in the menu.

### Steps to Reproduce
1. git clone https://github.com/kirienko/gourmet.git
2. cd gourmet
3. python3 setup.py install --user
4. gourmet
5. Go to Settings -> Plugins

### Expected Behavior
I would expect to see the plugins in the plugins menu and be available for e.g. printing.

### Current Behavior
No plugins are recognized or shown in the plugin menu.
The plugins also do not work, as can be tested by trying to print a recipe.
The plugin files are in place at the expected directory:
`~/.local/lib/python3.8/site-packages/gourmet-1.0.0-py3.8.egg/gourmet/plugins/`

### Possible Solution
If someone could point me to the code that searches for plugins and parses them, I can have a look at it.

### Environment
* Operating System: Ubuntu 20.04
* Version or commit id: ed1013b1f28bbc755a33fb31eab4b5a63f9e5c95
* Installed as Flatpak or Python package?: From source with setup.py

**Comment by cydanil** [comment]
Thanks!
I recommend that you use the wheel [as documented here](https://github.com/kirienko/gourmet/blob/master/INSTALL.md#python-wheel)

If you prefer to use the source, then it's a bit more convoluted, you need to [build the internationalization first](https://github.com/kirienko/gourmet/blob/master/CONTRIBUTING.md#setting-up-a-development-environment)

There's some work in progress [here (pull request 320)](https://github.com/kirienko/gourmet/pull/320) to make this easier in the future :)

**Comment by vollkorn1982** [comment]
Thanks a lot, i18n was the problem indeed and I didn't see the dev setup instructions. I prefer to having the dev setup, so if I encounter problems I can fix them and contribute.
