### ISSUE TITLE
Future feature request: is it possible to make a appimage for download

### ISSUE THREAD

**Issue by landerson78** [kirienko/gourmet#329]
appimages are alot easier than flatpak if u dont have the flatpak in the main flatpak page I would prefer appimage version if possible.

**Comment by Oldbwl** [comment]
I cannot see any development in the last few months. I too would like to continue to test this app, but cannot use my production machines with development flatpaks. I too would love to see an Appimage. - Actually, some information of the current position would be useful too.

**Comment by cydanil** [comment]
I was able to create an AppImage and to run it on Linux Mint and Fedora.
However, there's still some work to do: 

1) There's an error with signing the AppImage that I need to learn more about:
```
Could not read /home/runner/work/gourmet/gourmet/pubkey.asc: open /home/runner/work/gourmet/gourmet/pubkey.asc: no such file or directory.
```

2) Creating the AppImage on Ubuntu 20, but running it on Fedora 34 has a problem: `libffi.so` is version `6` on Fedora, but version `7` is expected by the AppImage.  
Creating a symlink resolves the issue:  `sudo ln -s /usr/lib64/libffi.so.6 /usr/lib64/lbffi.so.7`, but is a terrible idea!  

So we'll see what the coming days will bring.

**Comment by cydanil** [comment]
Thanks for your patience, I've created an AppImage here: https://github.com/kirienko/gourmet/releases/tag/v1.0.0-rc2

I'll close the ticket now, but should you encounter any issues, please report them here!
