### ISSUE TITLE
Flatpak out of date

### ISSUE THREAD

**Issue by hdholm** [kirienko/gourmet#330]
Using the flatpak for Version 1.0.0 RC 1 I get:
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.thinkle.Gourmet

**Comment by cydanil** [comment]
Thanks for reporting the issue, I did not keep track of what's happening in the flatpak world :)
