### ISSUE TITLE
Unable to Save

### ISSUE THREAD

**Issue by allenerenee** [kirienko/gourmet#339]
When I import a recipe from a website, or try to add one manually, the Save function in the recipe editor is non-functional. 

### Steps to Reproduce

1. Open the editor window and input/change information
2. Click 'save.' Button will do nothing.
3. Exit recipe editor. It will prompt you to save.
4. Click yes. The window will close, but the changes will not be saved.

### Expected Behavior
Information should be saved.

### Current Behavior
Save command is non-functional

### Environment

* Operating System:
System:
  Host: <filter> Kernel: 5.10.0-5mx-amd64 x86_64 bits: 64 compiler: N/A 
  parameters: ro root=UUID=<filter> 
  initrd=boot\initrd.img-5.10.0-5mx-amd64 
  Desktop: KDE Plasma 5.14.5 tk: Qt 4.8.7 wm: kwin_x11 dm: SDDM 
  Distro: MX-19.4_kde_x64 patito feo March 31  2021 
  base: Debian GNU/Linux 10 (buster) 
Machine:
  Type: Laptop System: LENOVO product: 20U3CTO1WW v: ThinkPad L15 Gen 1 
  serial: <filter> Chassis: type: 10 serial: <filter> 
  Mobo: LENOVO model: 20U3CTO1WW v: SDK0J40709 WIN serial: <filter> 
  UEFI: LENOVO v: R17ET25W (1.08 ) date: 12/08/2020 
Battery:
  ID-1: BAT0 charge: 47.1 Wh condition: 48.1/45.7 Wh (105%) volts: 12.4/11.1 
  model: Celxpert 5B10W13897 type: Li-poly serial: <filter> status: Unknown 
  cycles: 6 
CPU:
  Topology: Dual Core model: Intel Core i3-10110U bits: 64 type: MT MCP 
  arch: Kaby Lake family: 6 model-id: 8E (142) stepping: C (12) 
  microcode: DE L2 cache: 4096 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 20799 
  Speed: 815 MHz min/max: 400/4100 MHz Core speeds (MHz): 1: 815 2: 901 
  3: 834 4: 834 
  Vulnerabilities: Type: itlb_multihit status: KVM: VMX disabled 
  Type: l1tf status: Not affected 
  Type: mds status: Not affected 
  Type: meltdown status: Not affected 
  Type: spec_store_bypass 
  mitigation: Speculative Store Bypass disabled via prctl and seccomp 
  Type: spectre_v1 
  mitigation: usercopy/swapgs barriers and __user pointer sanitization 
  Type: spectre_v2 mitigation: Enhanced IBRS, IBPB: conditional, RSB filling 
  Type: srbds mitigation: TSX disabled 
  Type: tsx_async_abort status: Not affected 
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] vendor: Lenovo driver: i915 
  v: kernel bus ID: 00:02.0 chip ID: 8086:9b41 
  Display: x11 server: X.Org 1.20.10 driver: modesetting 
  unloaded: fbdev,vesa compositor: kwin_x11 resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 20.3.4 
  direct render: Yes 
Audio:
  Device-1: Intel Comet Lake PCH-LP cAVS vendor: Lenovo 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:02c8 
  Sound Server: ALSA v: k5.10.0-5mx-amd64 
Network:
  Device-1: Intel Ethernet I219-V vendor: Lenovo driver: e1000e v: kernel 
  port: efa0 bus ID: 00:1f.6 chip ID: 8086:0d4f 
  IF: eth0 state: down mac: <filter> 
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: efa0 
  bus ID: 04:00.0 chip ID: 8086:2723 
  IF: wlan0 state: up mac: <filter> 
Drives:
  Local Storage: total: 931.51 GiB used: 128.18 GiB (13.8%) 
  ID-1: /dev/sda vendor: Western Digital model: WD10SPSX-08A6W 
  size: 931.51 GiB block size: physical: 4096 B logical: 512 B 
  speed: 6.0 Gb/s rotation: 7200 rpm serial: <filter> rev: 1A01 scheme: GPT 
Partition:
  ID-1: / raw size: 48.83 GiB size: 47.81 GiB (97.92%) 
  used: 14.84 GiB (31.0%) fs: ext4 dev: /dev/sda6 
  ID-2: /home raw size: 642.58 GiB size: 631.49 GiB (98.27%) 
  used: 113.34 GiB (17.9%) fs: ext4 dev: /dev/sda8 
  ID-3: swap-1 size: 9.77 GiB used: 0 KiB (0.0%) fs: swap 
  swappiness: 15 (default 60) cache pressure: 100 (default) dev: /dev/sda7 
Sensors:
  System Temperatures: cpu: 46.0 C mobo: N/A 
  Fan Speeds (RPM): cpu: 0 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list 
  1: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ buster main
  Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
  1: deb http://deb.debian.org/debian buster-updates main contrib non-free
  Active apt repos in: /etc/apt/sources.list.d/debian.list 
  1: deb http://deb.debian.org/debian buster main contrib non-free
  2: deb http://deb.debian.org/debian-security buster/updates main contrib non-free
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
  1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/mx.list 
  1: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ buster main non-free
  2: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ buster ahs
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
  1: deb [arch=amd64] https://repo.skype.com/deb stable main
  No active apt repos in: /etc/apt/sources.list.d/various.list 
  Active apt repos in: /etc/apt/sources.list.d/winehq.list 
  1: deb https://dl.winehq.org/wine-builds/debian/ buster main
Info:
  Processes: 266 Uptime: 7h 41m Memory: 7.44 GiB used: 3.45 GiB (46.4%) 
  Init: SysVinit v: 2.93 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 
  Shell: quick-system-in running in: quick-system-in inxi: 3.0.36 

* Version or commit id:
* Installed as Flatpak or Python package?: Flatpak

**Comment by cydanil** [comment]
Thanks! I'll have a look tomorrow and keep you posted.  
I believe the issue was resolved already, but not released yet.

**Comment by cydanil** [comment]
Hi @allenerenee ,  
This issue was indeed previously fixed, but I have not made a new release yet with the fix.  

I also noticed a couple of other blocking issues I would like to resolve before creating a release.  
Stay tuned please! :)

**Comment by cydanil** [comment]
Thanks for your patience, I've created a new version here: https://github.com/kirienko/gourmet/releases/tag/v1.0.0-rc2  
A few more kinks, and we should be able to create a proper release :)
