### ISSUE TITLE
Save when not on last screen not working correctly

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#344]
Entering and saving a recipe, when not on last index page, saves 'New Recipe' and only partial data. Close application and re-open fixes entered recipe. I did not test entering new recipe when on last index page.

This test was done from the first index (Search Recipes tab) page.
Choose New in application menu
Fill in data for new recipe and save
Go to last index page to see 'New Recipe' in name column and some data in row
Double click 'New Recipe' and get switched back to edit window
Close edit window and double click opens mostly empty recipe card window with title 'New Recipe'
Close application
Re-open application, go to last index page and recipe appears as it should
Double click recipe and all data is present

### Expected Behavior
Adding new recipe, from any index page, should display index data when one goes to last index page
Double click on added recipe should show all entered and saved data

### Current Behavior
![Screenshot from 2021-06-18 10-44-01](https://user-images.githubusercontent.com/4460090/122581309-ea1b7480-d024-11eb-8273-30b325d0727b.png)
Showing last index page with edit window showing data entered and saved - ingredient and instruction data was entered, as well, but not shown here. Edit window was positioned to not hide any data showing on the index, only blank part of line.

![Screenshot from 2021-06-18 10-44-39](https://user-images.githubusercontent.com/4460090/122581517-1f27c700-d025-11eb-9048-9f9bb426c4ef.png)
Showing recipe card window after double clicking index item

![Screenshot from 2021-06-18 10-48-15](https://user-images.githubusercontent.com/4460090/122581821-72017e80-d025-11eb-890c-86d248a8fde2.png)
Result of double click after closing Gourmet and re-opening

### Environment
Ubuntu 20.04 (x86-64)
Kernel: 5.8.0-55-generic
Cinnamon 4.4.8
System and Python 3 kept up to date as updates are released
Commit: cb604da
There is no indication, in Help --> About, that this is RC2, but install completed normally
Installed as Flatpak

**Comment by cydanil** [comment]
This makes me sweat... :stuck_out_tongue: 

I'm on it, but it's difficult! I can't estimate how much work/time it is.

**Comment by zombiewoof** [comment]
Not a problem. It is working better than originally, just not 100%,
yet.

When you release a fix, can you put something into the version number
to indicate the RC number? Hopefully, that would be as simple as adding
something like 'RC' and the candidate number to a string containing the
version number. That would insure that I (and others) know that the
latest version did, indeed, install correctly.

**Comment by cydanil** [comment]
This problem is now resolved!  
I now need to fix the internationalization, and then will be able to create a new release.  
I'll take your suggestion into account :)  
Thanks!
