### ISSUE TITLE
Gourmet crashes when exporting recipes

### ISSUE THREAD

**Issue by ALTree** [kirienko/gourmet#346]
```
$ uname -a
Linux gauss 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux

$ python3 --version
Python 3.9.2
```

Installed from `gourmet-cb604da9-py3-none-any.whl`.

`File` -> `Export all Recipes` -> Press `OK`.

I would expect the recipes to be exported, but no file is created and:

```
Traceback (most recent call last):
  File "/home/alberto/.local/lib/python3.9/site-packages/gourmet/GourmetRecipeManager.py", line 1043, in <lambda>
    '<Control><Shift>T',_('Export all recipes to file'),lambda *args: self.do_export(export_all=True)),
  File "/home/alberto/.local/lib/python3.9/site-packages/gourmet/GourmetRecipeManager.py", line 703, in do_export
    self.exportManager.offer_multiple_export(
  File "/home/alberto/.local/lib/python3.9/site-packages/gourmet/exporters/exportManager.py", line 104, in offer_multiple_export
    fn,exp_type=de.saveas_file(_("Export recipes"),
  File "/home/alberto/.local/lib/python3.9/site-packages/gourmet/gtk_extras/dialog_extras.py", line 926, in saveas_file
    export_type = sfd.ext_to_filter[extension].get_name()
KeyError: ''

```

**Comment by cydanil** [comment]
Thanks for reporting the issue!  
The logs you provided are clear.  

I don't think the export file type you chose matters, but could you tell me which you chose?

**Comment by ALTree** [comment]
Definitely plain text and xml (the ones I tried), but I think it crashes on every file type.

**Comment by cydanil** [comment]
Thanks, 
I've made a preliminary fix which solves the issue, ~~the CI generated wheel is available here: [gourmet.zip]~~.  

Feel free to have a go at it, I'll be doing a bit more testing before closing the issue.

**Comment by cydanil** [comment]
The above wheels contains further bugs related to file selection, notably when setting images in a recipe.  
The fixes are now in master, and here's a wheel with them: [gourmet.zip](https://github.com/kirienko/gourmet/files/6709312/gourmet.zip)

**Comment by ALTree** [comment]
Thanks for the quick fix. Exporting now works.
