### ISSUE TITLE
State of the recipe import parsers

### ISSUE THREAD

**Issue by FriedrichFroebel** [kirienko/gourmet#35]
With #33, I started working on the existing import parsers (and intended to fix the remaining ones as well). While doing this, I stumbled upon some stuff which I am not sure about:

1. The tests rely on rather outdated local files, fixes to the code therefore will just satisfy the test cases, but not reflect the reality. As soon as someone tries to use the parser with the current site, it will break again and we have to re-write it. Should we therefore consider using the current site and parse the data from there? (See #20 as well.)

2. In my opinion the parser code is a bit weird (and I do not really get with it is a `preparse` and not a real parse). In the old version, it would create a list of tuples like this:

       [(Tag, 'recipe'), (Tag, 'title'), (Tag, 'ingredients'), (Tag, 'ingredients')]

    where `Tag` is a HTML element tag returned by BeautifulSoup. To get the list of ingredients later, we would iterate over this list and check whether the second tuple element matches the string `ingredients`. For me this does not look very efficient as we could use a dictionary `data['ingredients'] = ['ingredient1', 'ingredient2']` (or a simple data class) as well, where we might not even save the tags (I am not sure why they are saved in favor of their text, but I did not fully analyze the current code). With #33 I have switched to saving the texts instead of the tags, but this probably broke the real usage outside the tests.

    Do we want to change anything about it for now?

**Comment by cydanil** [comment]
Thanks.
I think in the first time, it makes sense to update the tests to reflect the current websites formats, as you propose in 1).  
For 2), your suggestion ultimately makes sense, but I would defer its implementation. We're at a stage now where we're trying the wrangle the code into something usable (ie. get the application to work as intended). As such, I find that such improvements would be very much welcome at a later time.

**Comment by micahcochran** [comment]
I wrote the library [scrape-schema-recipe](https://github.com/micahcochran/scrape-schema-recipe) for importing [schema.org/Recipe](https://schema.org/Recipe) format.  It is the format that most websites are using these days.  It returns the recipe a dictionary (see the link for more info).  When someone  tries to re-implement that functionality please take a look at this library.  Use it if it helps.

Thank you for updating gourmet!

**Comment by cydanil** [comment]
Thanks for the pointer @micahcochran, your library is looking pretty solid.

Currently, we'd like to get the application to work, in the first place. When we reach the point of making such improvements, we'll get back to it :)

**Comment by FriedrichFroebel** [comment]
With #53 the parsers have been updated to work with the latest websites - at least using the automated tests. For some of the parsers, I was actually able to build upon the work of @micahcochran (in fact I already had discovered this repository some weeks ago), while others still depend on custom formats. Currently all parsers are using the same approach as before (list of tuples), but have been switched to a consistent naming scheme (based on the names from the existing `schema_org_parser`). These changes might actually broke some GUI functionality, so I will keep this issue open for now until these bindings have been verified to work as expected.

**Comment by cydanil** [comment]
They now do. Thanks a lot for your help :)
