### ISSUE TITLE
Edit new recipe fails

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#357]
New recipe created and saved. Attempt to edit recipe after closing add window fails.

### Steps to Reproduce
Create a new recipe and save it.
Close edit window.
Choose recipe (I did this from Browse Recipes --> Category --> Bread Machine in this case).
Choose Edit from menu bar
Make edit.
Click Save and save edit fails.
![Screenshot from 2021-07-02 09-32-17](https://user-images.githubusercontent.com/4460090/124282769-2ff23580-db19-11eb-8e5d-35f2c4dc533b.png)
Note difference in recipe name between edit window and main window. Save button shows as clickable, even after clicking, and no change in recipe name. Closing edit window results in popup asking about saving. Choosing Save closes popup but save is not accomplished. Save still not applied if application is closed and re-opened.

### Expected Behavior
Save in edit window should save edits. Same for attempting to close the edit window, without saving, and clicking Save in the popup.

### Environment
gourmet-1.0.0
Operating System: Ubuntu 20.04 (x86-64) (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by cydanil** [comment]
Thanks for being so thorough!  
There are many parts of Gourmet, and I'm not aware of all of them just yet, and so I don't always test each functionality exhaustively.  

I've fixed the issue, and will make a small release soon :)
