### ISSUE TITLE
Printing and Export not functioning

### ISSUE THREAD

**Issue by sdunbarne** [kirienko/gourmet#368]
Printing and Export not functioning

### Steps to Reproduce

1.  Choose:  Recipe > Print > Print to file dialog box, choose pdf, Print, dialog box disappears, nothing printed  
2.  Choose: Recipe > Export > Save Recipe dialog box, choose pdf, dialog box disappears, no pdf file
3.  Choose: Recipe > Export > Save Recipe dialog box, choose HTML, export is partial, just Description and Ingredients, no Instructions or Notes.

### Expected Behavior

Either PDF or HTML file

### Environment

* Operating System:  Fedora 33, all current updates, with KDE/Plasma 
* Version or commit id:  Gourmet 1.0.1
* Installed as Flatpak or Python package?:  Installed as Flatpak

**Comment by cydanil** [comment]
Thanks, this is the same issue as #313.  
This is due to the fonts not being available within the flatpak environment.  

While this will be addressed,  perhaps you could try the AppImage in the meantime?

**Comment by cydanil** [comment]
I'm now working on this, but will close this issue as a duplicate of #369, where the discussion will be :)
