### ISSUE TITLE
Ubuntu 20.04 required for CI

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#39]
In the CI, the version of Ubuntu currently targeted is `ubuntu-latest`, which is 18.04 under the hood.

In this version of Ubuntu, the provided version of `PyGObject` does not have the key feature [`Pango.AttrList.get_iterator()`](https://developer.gnome.org/pygtk/stable/class-pangoattrlist.html#method-pangoattrlist--get-iterator), used by many parts of the application to where free-text is accepted (eg. entering the instructions of a recipe).

We can test this by doing the following:

```python
In [1]: import gi

In [2]: gi.require_versions({'Gtk': '3.0', 'Pango': '1.0'})

In [3]: from gi.repository import Pango

In [4]: hasattr(Pango.AttrList,'get_iterator')
Out[4]: False
```

Ubuntu 20.04 has the latest version of libpango, and I confirmed that this test passes.

We are aware that [Github is working on getting `ubuntu-latest` to be 20.04](https://github.com/actions/virtual-environments/issues/228#issuecomment-622256916), but it's not there yet.

As such, most test won't pass, even if they're correct.

As we aim to target the libraries of Ubuntu 20.04 or equivalent, I suggest to wait it off until `ubuntu-latest` is 20.04, as we have plenty to do before anyway.

However, we are open to a contribution that would update the CI to make use of Ubuntu 20.04! :smile: 

Note that we have not tried tested this behaviour on Ubuntu 19.04.  
Users of the latest Linux Mint (Tricia), will also run into this issue.

**Comment by maweki** [comment]
Just the say it here again: I think it is fine to target Ubuntu 20.04+. We can ignore distributions where python2 is still shipped out of the box, as gourmet is available and "supported" there. We're doing what we're doing because things have moved along so far.
