### ISSUE TITLE
Make languages into classes

### ISSUE THREAD

**Issue by maweki** [kirienko/gourmet#64]
Currently, languages from `gourmet/defaults/` are dynamically included modules that all behave the same. I don't think, we can get `mypy` to correctly type them. As it is just a set of fields and two methods that are all there by convention, I propose we change that in the language files to a (static) class that gets exported by `gourmet/defaults/defaults.py`. This wouldn't change the interface, but would change the type from just `module` to `LanguageClass`, allowing `mypy` to properly inspect that.

If you agree, I would be willing to do that and then I could start cleaning up after other people's improvements to get the type hints at the interfaces correctly.

**Comment by cydanil** [comment]
What you propose makes sense. However, is there a way to verify that it will still work as intended afterwards?

**Comment by maweki** [comment]
> is there a way to verify that it will still work as intended afterwards?

As languages are loaded immediately, I think it will break instantly otherwise. But all in all, currently the `lang` name points to the specific language module that just contains the names (verbs and stuff). Then we will have the class that has this as attributes. The accessors will still be `lang.stuff`, only that `type(lang)` is no longer `module` but `LanguageClass`.

If there is no very strange import through the specific language module (which I don't believe, as the language import is dynamic/strange), this will be a transparent change. If I find an import that goes right into the module, I can just change that from `import foo from lang` to `import lang` and the call from `foo.stuff` to `lang.foo.stuff`. But I am confident, that this won't be an issue.

**Comment by cydanil** [comment]
Ok, I'm satisfied with this plan.

**Comment by maweki** [comment]
We maybe want to type the differnt types of strings and amounts, etc. differently. But for the time being, this is fine.
