### ISSUE TITLE
recindex.py: sort() takes no positional arguments

### ISSUE THREAD

**Issue by maweki** [kirienko/gourmet#7]
```
Traceback (most recent call last):
  File "./gourmet/recindex.py", line 319, in <lambda>
    get_colnum(tc),
  File "./gourmet/convert.py", line 573, in seconds_to_timestring
    units.sort(lambda a,b: a[1]<b[1] and 1 or a[1]>b[1] and -1 or 0)
TypeError: sort() takes no positional arguments
```

This needs to be a new-style key function. If we don't want to write our own, we can use https://docs.python.org/3/library/functools.html#functools.cmp_to_key to create one from the given function. `List.sort()` takes the argument as keyword-arg `key` (https://docs.python.org/3/library/stdtypes.html#list.sort) but we might want to rewrite a bit of this section.

This is an easy fix and I am happy to do it tomorrow.

**Comment by kirienko** [comment]
There is a test for that already: https://github.com/kirienko/gourmet/blob/master/gourmet/test_convert.py

But we might need to fix the logic of that test itself :)

**Comment by maweki** [comment]
> There is a test for that already:

Well, not for `seconds_to_timestring`. It throws an exception.
