### ISSUE TITLE
Consider removing custom styling in RecCardDisplay

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#72]
I'd like to remove the custom styling in `RecCardDisplay`, implemented [here in `setup_style`](https://github.com/kirienko/gourmet/blob/4d05aac236ef8ab71d27cde1256acef6a7b6377f/gourmet/reccard.py#L354)

This is the view for a recipe. The current Gtk2 code is outdated, and needs to be ported to Gtk3, and is major blocker for fixing the record card and its tests.

I've done it, and I find the result horrible:
![with_custom_styling](https://user-images.githubusercontent.com/2159577/82082772-dcd8db80-96e8-11ea-8fc8-3e028b9492ca.png)

Whereas the default theme, which depends on your desktop environment settings, looks so for me (xfce4 with the Linux Mint-Y theme):

![default_theme](https://user-images.githubusercontent.com/2159577/82082947-2e816600-96e9-11ea-9cf4-bdacd2c2e602.png)

By removing it, we also remove questionable code.

(unrelated, the recipe is `hot chocolate with a twist for cold evenings`)

**Comment by maweki** [comment]
I think this looks great. Proper client side styling has evolved very much and the system widgets are perfectly fine.

We can re-add css rules later on, if we find some elements lacking.
