### ISSUE TITLE
GtkComboBoxText should be editable

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#90]
`ComboboxText` are used for all drop down menus.

However, these are not editable, in places where I think they ought to be, such as the yielded portions units, categories, cuisine, and sources in the record editor.

![image](https://user-images.githubusercontent.com/2159577/83692083-9bef2b00-a5f3-11ea-8541-0b47f5d16a17.png)

I'm not sure it historically was handled. Could someone shed some light on the matter?
Thanks!

**Comment by maweki** [comment]
Just as a reference: I explained the changes with gtk3 a little bit here: https://github.com/kirienko/gourmet/pull/43

We need `ComboBox.new_with_entry()` to get a combobox with an editable cell, as long as the documentation isn't lying.
